name: Determine Version

on:
  push:
    branches:
      - main
    paths-ignore:
      - "package.json"
      - "src/util/version.ts"
      - "CHANGELOG.md"

jobs:
  determine-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Determine next version (dry-run)
        id: semrel
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog

      - name: Update version file
        if: steps.semrel.outputs.new_release_version
        run: |
          NEXT_VERSION="${{ steps.semrel.outputs.new_release_version }}"
          echo "export const APP_VERSION = \"$NEXT_VERSION\";" > src/util/version.ts
          echo "Using semantic-release determined version: $NEXT_VERSION"

      - name: Commit version update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update `version.ts`"
          file_pattern: src/util/version.ts
